### ISSUE TITLE
Test with https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/MobileMapStarter2#16]
Reported by Andrew G:

https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated

I use this plugin to load static images as a basemap for maps that cover a small area. It works correctly on Android 6.3.2, though when testing on my emulator it only displays properly at the closest zoom level.

**Comment by TinArgus** [comment]
I was emulating on Android 4.0.3 when having this problem. In the Android 6.x and 7.x environment it works fine on an emulator, so the issue must be in 4.0.x

On my Galaxy S4 phone running 4.2.2, the images load properly but the boundaries become deformed after zooming around (similar to [Issue 15](https://github.com/GreenInfo-Network/MobileMapStarter2/issues/15))

**Comment by gregallensworth** [comment]
* Could I see some sample code (e.g. the image and map extent) so I can give this a try? We can go with direct message if you'd prefer not to share it in this public forum.

I've not been able to get into this one yet, though it has not been forgotten. I won't be able to get back to it until next week, on account of some construction work separating me from my mobile testing platforms for a few days, but I do want to check into it.

At best, we can work around the issue on these old platforms (which are not dead yet!), and least we can document them as a known issue.

**Comment by gregallensworth** [comment]
I am able to confirm this issue with the ImageOverlay.Rotated layer on Android 4.2 in an emulator, and to confirm that the problem is absent in Android 70 in an emulator.

The issue does seem restricted to the ImageOverlay.Rotated The tile layers seem to sync well with the vector trail.

The overlaid image does display at some levels, but it's spotty. When it does display, its matchup to the vector trail is obviously incorrect, and the image is displaying at varying resolutions. At some levels it seems to act more like a video glitch than an image, leaving traces of green here and there instead of the lines depicted. These failures are very consistent, though: the same problems at the same levels, between runs.

This would seem to be an incompatibility with ImageOverlay.Rotated and the web view used in Android 4...

**Comment by gregallensworth** [comment]
Thumbing through the code for ImageOverlay.Rotated I think this is an incompatibility.

Reference:
* http://caniuse.com/#feat=transforms2d
* https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated/blob/gh-pages/Leaflet.ImageOverlay.Rotated.js#L148

ImageOverlay.Rotated uses some CSS transforms, and Android before 4.4 didn't support such transforms. At 4.4 Android supports transforms only with the `-webkit-` prefix.

You could try rotating your image, then using a plain ImageOverlay which uses different transforms. However on 4.2 this may still not work, as ImageOverlay (non-rotated) does still use scale transforms.

**Comment by TinArgus** [comment]
Glad to know that you were able to recreate the problem and isolated it to the Image Overlay. I'm glad that it is only pre-4.4 Android that has issues...there wont be too many of those devices trying to install my app (hopefully). Thanks for the additional references and for helping to troubleshoot the issue!

**Comment by TinArgus** [comment]
I can confirm that plain old ImageOverlay will work with Android 4.2 although the image briefly disappears with each zoom level change until the CSS hack corrects it. I haven't been able to get the rotation and orientation quite right yet, but it is good to know that there is a method that works on the older systems.
