### ISSUE TITLE
SCSS adjustment to $appcontent-background-color

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/MobileMapStarter2#17]
Reported by @TinArgus

* I wanted to change the color of the background on the main content pages, and thought I could accomplish this by changing $appcontent-background-color
* However, this only changes the base color behind the page, and the page remains white.
* it is in fact the section class which needs to be modified
* I added it to the bottom of the maincontent.scss file and had it reference $appcontent-background-color

**Comment by TinArgus** [comment]
Here is the code that I added to the end of /www/style/maincontent.scss to let $appcontent-background-color control the color of the section class in the main pages:

`.section{background-color: $appcontent-background-color;}`

**Comment by gregallensworth** [comment]
Brilliant. Thanks so much TinArgus. I have integrated this change, and it will make it into the next release.
