### ISSUE TITLE
OSM App Restrictions and Alternative Tile Layers

### ISSUE THREAD

**Issue by TinArgus** [GreenInfo-Network/MobileMapStarter2#18]
I was reading up on [Open Street Map](https://operations.osmfoundation.org/policies/tiles/) and found that they are generally against their tile servers being used in apps. 

You can request permission for an exception, but people who leave OSM in their app and neglect to get permission might eventually run in to issues with OSM blocking access if they get too many users.

I haven't found the same restrictions with the ESRI tile servers that this project uses, though the policies there are a lot more dense and I haven't read through everything.

There is a [really nice topo map](https://opentopomap.org/) from Open Topo Map and they encourage people to use their servers in app projects. I successfully loaded this layer in MobileMapStarter in online mode, but for some reason it will not display properly when downloaded and displayed in offline mode. It goes through the motions and appears to download the data, but doesn't show on the map. 

Is there something I need to do other than changing the url in settings.js to make this work? As a possible alternative to using tile servers, how would I go about including a set of downloaded tiles with the release to make it offline from the start and avoid the need for a server connection?

**Comment by gregallensworth** [comment]
You make a good point about the OSM tiles. I wouldn't normally consider the intended usage here (a demo which folks would swap out) to be "heavy", however the tile-downloading system *does* seem to invite heavy usage after all, particularly if one were just starting with MMS and running a lot of tiles as they got familiar. Good thinking here.

Let's see...
* OpenTopoMap would use this URL template `https://{s}.tile.opentopomap.org/{z}/{y}/{x}.png`
* and should of course be mentioned in the About page where I stick some starting credits & attributions...

**Comment by gregallensworth** [comment]
There we go.
* OSM is out and OpenTopo is in.
* ESRI Topo replaced with ESRI World Street Map, since we now have a topo.
* Map Settings page updated with new layer list.
* About page updated with new credits.

The OpenTopo map worked A-OK for me, including offline usage. I don't see any reason it wouldn't, and I didn't need to make any special changes to make it work: just update settings and the map settings UI where I pick layers.
