### ISSUE TITLE
API 26

### ISSUE THREAD

**Issue by TinArgus** [GreenInfo-Network/MobileMapStarter2#22]
In updating an app, I noticed that the android API that this uses will only be supported by Google for a few more months.

See https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

 I still actively use this project - would it take much to update this to API 26? Thanks!

**Comment by gregallensworth** [comment]
Thanks for keeping an eye on this. I appreciate that.

I have updated `master` to `cordova-android` 7.0.0 According to https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html this supports API levels 19-27, aka Android OS 4.4 - 8.1

I'll do some more testing and work here, and may have a new release today or tomorrow if nothing seems newly awry.

**Comment by gregallensworth** [comment]
Please give the **1.2.0 release** a look, and let me know what you think. This uses the current iOS and Android plugins, as well as other updates to the npm tools. Seems to work A-OK here in Xcode and Android Studio.

**Comment by TinArgus** [comment]
Thanks for getting on this so quickly and keeping this project alive! I cannot stress how much it has helped me. I was able to get this version to work after a little effort but I noticed some issues with the way the app is working. Every time I go to the map settings page, I get the ` this.modalMessageShow('No layers have offlineCache enabled.', 'No Layers Found');` error. It also appears that for the three default base layers that 'offlineCache:true' needs to be within the options of the layer to work. One other issue - the 'opentopo' basemap does not load when the app starts like it is supposed to, and has to be manually clicked. Otherwise things look good! Hopefully these two remaining issues are easy to resolve! Note: this testing was done for Android using an emulator on Windows

**Comment by gregallensworth** [comment]
* Every time I go to the map settings page, I get the this.modalMessageShow('No layers have offlineCache enabled.', 'No Layers Found'); error.

I did see that when using Android Studio, as A.S. was not loading Cordova/Phonegap. If you're using Android Studio, install the Cordova plugin. This is in the Settings menu, and hidden in a sub-button called JetBrains Plugins.

After installing that, it began working in Android Studio just fine.

Can you give that a try, and let me know how it goes? If it's not well, I would need more details as to the setup.

**Comment by TinArgus** [comment]
I fumbled through some NPM and Yarn updates and alas, all of the problems resolved themselves! As far as I can tell, the updated version is good to go. Thanks again for your help!

**Comment by gregallensworth** [comment]
You're very welcome! Thank you for your interest.

The npm and yarn updates, and that unstated step about installing a hidden plugin for Android Studio, ... had me chasing my tail for 4 hours this morning!
