### ISSUE TITLE
AR in MMS2

### ISSUE THREAD

**Issue by TinArgus** [GreenInfo-Network/MobileMapStarter2#24]
How difficult would it be to have augmented reality added to this platform? I am mostly interested in overlaying .geojson features on an AR view. I found several projects that seem to be compatible with Cordova, but am not sure which would work best.

https://github.com/Wikitude/wikitude-cordova-plugin

https://github.com/tjwoon/csAR

https://github.com/OutSystems/cordova-outsystems-google-ar-core

https://github.com/taqtile-us/cordova-plugin-ARKit

https://github.com/Danh-134/Cordova-ARjs

https://github.com/phfsoares/cordova-plugin-ar

**Comment by danrademacher** [comment]
This is totally outside our interest and expertise, so if you wanted to pursue it, you'd need to fork this repo and take it on yourself or with others. Sounds cool though!
